### ISSUE TITLE
Distinction between different kinds of `InvalidExpression`s

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/kernel#11]
We should probably distinguish between different kinds of `InvalidExpression`s.

Most of them should probably be translated to `NoSuchMethodError`s, e.g. `tests/co19/src/Language/Expressions/Instance_Creation/New/named_constructor_t02.dart`:

```
class C<T> {}
  
main() {
  Expect.throws(
    () {new C<int>.namedConstructor();}, /// static warning - unavailable named constructor, see "Instance creation|New"
    (e)=> e is NoSuchMethodError
  );  
}
```

There are many more tests of this kind.

There might be other errors which the spec defines as compile-time errors which we might want to handle differently.

/cc @asgerf @peter-ahe-google

**Comment by asgerf** [comment]
The high-level issue here is the same as https://github.com/dart-lang/kernel/issues/7, so I'm closing this one.  (The concrete test case in the original post has been fixed, but there are still issues).
