### ISSUE TITLE
Fall-Through SwitchCases 

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/kernel#12]
Currently a kernel IR file can have invalid fall through to the next case. The Dart language specification mandates this to be a runtime error. The DartVM throws an exception of type `FallThroughError`.

We should think about whether all backends should handle it or the kernel IR generator should do it.

/cc @peter-ahe-google @asgerf

**Comment by asgerf** [comment]
Fixed in 1906e420431656d351a9f4ee9a36b8ca9a4da1db
