### ISSUE TITLE
Could not find required library dart:profiler

### ISSUE THREAD

**Issue by jameyhicks** [dart-lang/kernel#26]
Where do I find library dart:profiler and dart:_vmservice?

```
bash-3.2$ ../kernel/bin/dartk.dart -o foo.dill -l test.dart
../kernel/bin/dartk.dart -o foo.dill -l test.dart
Could not find required library dart:profiler
Could not find required library dart:_vmservice
bash-3.2$ dart --version
dart --version
Dart VM version: 1.20.0-dev.5.0 (Tue Sep 13 13:42:48 2016) on "macos_x64"
```

test.dart:
```
void main() {
     print("hello");
}
```

**Comment by jameyhicks** [comment]
As a workaround, I can use -t none because it is the vm target that needs those libraries.

**Comment by asgerf** [comment]
Using `-tnone` is the only way to compile based on a released Dart SDK. Depending on your use case, that may be all you need.

If you need to execute the generated code, you need the VM target, and for that you need a custom SDK build based on [kernel_sdk](https://github.com/dart-lang/kernel_sdk). The build instructions are on the wiki for that repository, but note that the build tools can be a bit rough. After building the `runtime` target, an SDK that supports the VM target can be found in `kernel_sdk/out/DebugX64/obj/gen/patched_sdk`.

**Comment by jameyhicks** [comment]
Thank you for the information. I will see if I need to build the kernel_sdk.
