### ISSUE TITLE
Closure conversion: super calls

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/kernel#35]
Closure conversion needs to be able to handle super calls in hoisted functions.

**Comment by asgerf** [comment]
Initially we can just do closure conversion after mixin resolution.

But that does not support modular compilation, nor does it support runtime resolution of mixins, which JS compilers need. Progress on this is blocked by two conflicting features in the language: super calls in mixins, and allowing a mixin applied multiple times in a class hierarchy. I personally think the latter is a useless feature that we should just drop, but I haven't been able to get a clear ruling from the language team.

**Comment by peter-ahe-google** [comment]
Does mixin resolution also address the fact that `super` implicitly refers to `this`, but `this` gets rewritten to `this.self`?

**Comment by asgerf** [comment]
Yes, a super call is rewritten to a direct call with a ThisExpression as receiver. If we run closure conversion afterwards, it should pick up the ThisExpression without needing any special treatment for super calls.

**Comment by peter-ahe-google** [comment]
That's good. I'll close this issue for now.
